### ISSUE TITLE
Setup unit test

### ISSUE THREAD

**Issue by ajainvivek** [ajainvivek/preact-fluid#1]
Description:

- Setup unit test 
- Hook unit test to BUILD & PUSH
- Test at least one basic component (eg. Link)

Reference:

- https://preactjs.com/guide/unit-testing-with-enzyme

**Comment by enthudrives** [comment]
Taken

**Comment by sabeurthabti** [comment]
@ajainvivek would this be something to consider ? https://github.com/ruyadorno/preact-jest-snapshot-test-boilerplate:

snapshot testing + enzyme.

**Comment by ajainvivek** [comment]
@sabeurthabti will have a look at the repo. If you wish to become a contributor, please let me know.

**Comment by sabeurthabti** [comment]
That would be good, feel free to make me a contributor. I will keep raising PRs.

**Comment by ajainvivek** [comment]
@sabeurthabti I have added you as a collaborator. Please feel free to share your thoughts and improve.

**Comment by ajainvivek** [comment]
The test suite is setup 👍
