### ISSUE TITLE
Code in the npm package is not the newest one

### ISSUE THREAD

**Issue by raqso** [ajainvivek/preact-fluid#15]
I've noticed that package from the npm, doesn't have the disabled buttons change yet. Could you possibly update this?
Thank you in advance.

**Comment by sabeurthabti** [comment]
@raqso will try to do a release tonight.

**Comment by sabeurthabti** [comment]
@ajainvivek I pushed a tagged build and it didn't work. 
https://travis-ci.org/ajainvivek/preact-fluid/jobs/494599169

I don't understand travis much.

**Comment by ajainvivek** [comment]
@sabeurthabti I have fixed the travis CD pipeline, now bumping version in `package.json` and tag release using `npm run release` should deploy new changes to `npm` registry

Released new version 👍
