### ISSUE TITLE
propTypes static error

### ISSUE THREAD

**Issue by sabeurthabti** [ajainvivek/preact-fluid#3]
Awesome project - however I am running into some issues:

I keep getting the following error:

```
/Users/sabeur/workspace/x/node_modules/preact-fluid/src/Card/CardFooter.js:11:18: Unexpected token (11:18)
   9 |  */
  10 | class CardFooter extends Component {
> 11 |  static propTypes = {
     |                   ^
  12 |          /**
  13 |           * Custom styles
  14 |           */

```
babelrc:

```
"presets": ["env", "es2015", "stage-2", "stage-0"],
... and
"transform-class-properties"
```
would it make sense to compile the project to a dist folder ?

**Comment by ajainvivek** [comment]
@sabeurthabti Yes, I agree. I can give a try this weekend. If you can create a PR that would also be perfect.

**Comment by sabeurthabti** [comment]
Awesome I will try over the weekend.

**Comment by ajainvivek** [comment]
The changes are merged and published 👍 🥇
