### ISSUE TITLE
Demo page broken 

### ISSUE THREAD

**Issue by ajainvivek** [ajainvivek/preact-fluid#7]
@sabeurthabti the demo website is broken. Can you please look into it?

**Comment by sabeurthabti** [comment]
done

**Comment by ajainvivek** [comment]
awesome 👍

**Comment by sabeurthabti** [comment]
I spent an hour trying to fix this issue, even going back in git history in case it was resent bug. 

`styleguidist server` seems to work fine, however the `build` keep generating a bad bundle.

@ajainvivek can you try running `npm run styleguide-build` on your side ? thanks
