### ISSUE TITLE
Way to create password text input?

### ISSUE THREAD

**Issue by jaooe** [ajainvivek/preact-fluid#8]
Currently the text field doesn't provide a way to create an password-type input?

EDIT:

Have created a PR to solve this issue: https://github.com/ajainvivek/preact-fluid/pull/9

**Comment by ajainvivek** [comment]
@jaooe looks like the PR is merged. Closing the issue.

**Comment by sabeurthabti** [comment]
@jaooe released: https://www.npmjs.com/package/preact-fluid

 `+ preact-fluid@0.7.0`

**Comment by konsumer** [comment]
I am having similar issues with un-managed forms (`onChange` handler needs access to `name` or `id`.) I've been letting the browser manage values, and just run `onChange` for passive validation. It tends to be simpler and more robust for me.

Would it make sense  to pass props to the `<input />` tag with `{...props}`?

It would make this sort of thing work:

```
const onChange = e => {
  const { name, value } = e.target
  // do stuff with name & value
}


<TextField
      label='Email'
      type='email'
      name='email'
      placeholder='user@host.com'
      effect='lineOutwards'
      onChange={onChange}
      errorText={errors.email}
    />
```

**Comment by konsumer** [comment]
`<Button disabled />` is also sort of similar.
